---
title: "GTFS_Peo"
output: html_document
date: '2023-02-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages('tidytransit')
library(tidyverse)
library(tidytransit)
```

```{r}
gtfs <- read_gtfs("http://data.trilliumtransit.com/gtfs/ridecitylink-il-us/ridecitylink-il-us.zip")
gtfs <- set_servicepattern(gtfs)
gtfs <- gtfs_as_sf(gtfs)
```

```{r}
require("knitr")
opts_knit$set(root.dir = "C:/Users/Siddhesh.Kudale/OneDrive - Lochmueller Group/")
getwd()

stops <- read_csv("stops.txt", trim_ws = T)
trips <- read_csv("trips.txt", trim_ws = T)
agency <- read_csv("agency.txt", trim_ws = T)
stoptime <- read_csv("stop_times.txt", trim_ws = T)
routes <- read_csv("routes.txt", trim_ws = T)
shapes <- read.csv("shapes.txt")
```

```{r}
n = leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addCircleMarkers(data = stops, lng = ~stop_lon, lat = ~stop_lat, stroke = FALSE, fillOpacity = 0.7, radius = 2)
n
```

```{r}
agency_filter = "CityLink"
agency_name = "CityLink"

peoria = agency %>% 
  select(agency_id) %>%
  filter(str_detect(agency_name, agency_filter))%>% 
  inner_join(select(routes, route_short_name, agency_id, route_id, route_type)) %>%
  inner_join(select(trips,route_id,trip_id)) %>% 
  inner_join(select(stoptime, trip_id, stop_id)) %>% 
  select(-trip_id) %>% unique() %>% 
  inner_join(select(stops, stop_id, stop_name, lat = stop_lat, lon = stop_lon))
```

```{r}
peoria$transport_mode <- ifelse(peoria$route_type == "3", 'Bus')
```

```{r}
pal <- colorFactor(palette = c("#91148d", "#145d91","#14912d","#8d9114"), domain = peoria$transport_mode)
```

```{r}
peoria_cnt = agency %>% 
  select(agency_id) %>%
  filter(str_detect(agency_name, agency_filter))%>% 
  inner_join(select(routes, route_short_name, agency_id, route_id, route_type)) %>%
  inner_join(select(trips,route_id,trip_id)) %>% 
  inner_join(select(stoptime, trip_id, stop_id)) %>% 
  group_by(agency_id, route_type, stop_id) %>% 
  summarise(cnt =n()) %>% 
  inner_join(select(stops, stop_id, stop_name, lat = stop_lat, lon = stop_lon))

peoria$transport_mode <- ifelse(peoria$route_type == "3", 'Bus')

peoria_cnt = peoria_cnt %>% 
  group_by(peoria_cnt$route_type) %>% 
  mutate(bin = ntile(cnt, n = 10))

pal <- colorFactor(palette = c("#91148d"), domain = peoria_cnt$transport_mode)

mn = leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addCircleMarkers(data = peoria_cnt, lng = ~lon, lat = ~lat, stroke = FALSE, fillOpacity = 0.5, radius = ~(bin)) %>% addLegend("bottomright", pal = pal, values = agency_name, title = "Frequency of Use by Operator, 2021", opacity = 0.5)
mn
```

```{r}
head(gtfs$.$dates_services)
library(lubridate)
gtfs <- set_servicepattern(gtfs)
```


```{r}
holidays = tribble(~date, ~holiday,
  ymd("2018-07-04"), "Independence Day",
  ymd("2018-09-03"), "Labor Day")

calendar = tibble(date = unique(gtfs$.$dates_services$date)) %>% 
  mutate(
    weekday = (function(date) {
      c("Sunday", "Monday", "Tuesday", 
        "Wednesday", "Thursday", "Friday", 
        "Saturday")[as.POSIXlt(date)$wday + 1]
    })(date)
  )

calendar <- calendar %>% left_join(holidays, by = "date")
head(calendar)
```

```{r}
head(gtfs$.$servicepatterns)
n_services <-  length(unique(gtfs$trips$service_id)) # 70
n_servicepatterns <- length(unique(gtfs$.$servicepatterns$servicepattern_id)) # 7
```


```{r}
date_servicepattern_table <- gtfs$.$dates_servicepatterns %>% left_join(calendar, by = "date")

ggplot(date_servicepattern_table) + theme_bw() + 
  geom_point(aes(x = date, y = servicepattern_id, color = weekday), size = 1) + 
  scale_x_date(breaks = scales::date_breaks("1 month")) + theme(legend.position = "bottom")
```


```{r}
suggest_servicepattern_name = function(dates, calendar) {
  servicepattern_calendar = tibble(date = dates) %>% left_join(calendar, by = "date")
  
  # all normal dates without holidays
  calendar_normal = servicepattern_calendar %>% filter(is.na(holiday))
  
  # create a frequency table for all calendar dates without holidays
  weekday_freq = sort(table(calendar_normal$weekday), decreasing = T)
  n_weekdays = length(weekday_freq)
  
  # all holidays that are not covered by normal weekdays anyways
  calendar_holidays <- servicepattern_calendar %>% filter(!is.na(holiday)) %>% filter(!(weekday %in% names(weekday_freq)))

  if(n_weekdays == 7) {
    pattern_name = "Every day"
  }
  # Single day service
  else if(n_weekdays == 1) {
    wd = names(weekday_freq)[1]
    # while paste0(weekday, "s") is easier, this solution can be used for other languages
    pattern_name = c("Sunday"  = "Sundays", 
        "Monday"    = "Mondays", 
        "Tuesday"   = "Tuesdays", 
        "Wednesday" = "Wednesdays",
        "Thursday"  = "Thursdays",  
        "Friday"    = "Fridays",  
        "Saturday"  = "Saturdays")[wd]
  } 
  # Weekday Service
  else if(n_weekdays == 5 && 
      length(intersect(names(weekday_freq), 
        c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))) == 5) {
    pattern_name = "Weekdays"
  }
  # Weekend
  else if(n_weekdays == 2 && 
      length(intersect(names(weekday_freq), c("Saturday", "Sunday"))) == 2) {
    pattern_name = "Weekends"
  }
  # Multiple weekdays that appear regularly
  else if(n_weekdays >= 2 && (max(weekday_freq) - min(weekday_freq)) <= 1) {
    wd = names(weekday_freq)
    ordered_wd = wd[order(match(wd, c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")))]
    pattern_name = paste(ordered_wd, collapse = ", ")
  } 
  # default
  else {
    pattern_name = paste(weekday_freq, names(weekday_freq), sep = "x ", collapse = ", ")
  }
  
  # add holidays
  if(nrow(calendar_holidays) > 0) {
    pattern_name <- paste0(pattern_name, " and ", paste(calendar_holidays$holiday, collapse = ", "))
  }
  
  pattern_name <- paste0(pattern_name, " (", min(dates), " - ", max(dates), ")") 

  return(pattern_name)
}
```


```{r}
servicepattern_names = gtfs$.$dates_servicepatterns %>% 
  group_by(servicepattern_id) %>% summarise(
    servicepattern_name = suggest_servicepattern_name(date, calendar)
  )

print(servicepattern_names)
```

```{r}
dates = gtfs$.$dates_servicepatterns
dates$wday <- lubridate::wday(dates$date, label = T, abbr = T, week_start = 7)
dates$week_nr <- lubridate::week(dates$date)

dates <- dates %>% group_by(week_nr) %>% summarise(week_first_date = min(date))%>% right_join(dates, by = "week_nr")

week_labels = dates %>% select(week_nr, week_first_date) %>% unique()

ggplot(dates) + theme_bw() +
  geom_tile(aes(x = wday, y = week_nr), color = "#747474") +
  scale_x_discrete(drop = F) +
  scale_y_continuous(trans = "reverse", labels = week_labels$week_first_date, breaks = week_labels$week_nr) +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = NULL, y = "Date of Start of Week") +
  facet_wrap(~servicepattern_id, nrow = 1)
```

```{r}
trips_servicepattern = left_join(select(gtfs$trips, trip_id, service_id), gtfs$.$servicepatterns, by = "service_id")
trips_servicepattern2 = left_join(trips, routes, by = "route_id")
trips_servicepattern2 = trips_servicepattern2[,c(1:3),]
trips_servicepattern = left_join(trips_servicepattern, trips_servicepattern2, by = "service_id")
trips_servicepattern = trips_servicepattern[,c(1:4),]
trip_dates = left_join(gtfs$.$dates_servicepatterns, trips_servicepattern, by = "servicepattern_id")

trip_dates_count = trip_dates %>% group_by(date, route_id) %>% summarise(count = dplyr::n()) 
trip_dates_count$weekday <- lubridate::wday(trip_dates_count$date, label = T, abbr = T, week_start = 7)
trip_dates_count$day_of_month <- lubridate::day(trip_dates_count$date)
trip_dates_count$first_day_of_month <- lubridate::wday(trip_dates_count$date - trip_dates_count$day_of_month,  week_start = 7)
trip_dates_count$week_of_month <- ceiling((trip_dates_count$day_of_month - as.numeric(trip_dates_count$weekday) - trip_dates_count$first_day_of_month) / 7)
trip_dates_count$month <- lubridate::month(trip_dates_count$date, label = T, abbr = F)
trip_dates_count <- trip_dates_count %>%
  mutate(count = count/20)

ggplot(trip_dates_count, aes(x = weekday, y = -week_of_month)) + theme_bw() +
  geom_tile(aes(fill = count, colour = "grey50")) +
  geom_text(aes(label = day_of_month), size = 3, colour = "grey20") +
  facet_grid(vars(month), vars(route_id)) +
  scale_fill_gradient(low = "cornsilk1", high = "DarkOrange", na.value="white")+
  scale_color_manual(guide = "none", values = "grey50") +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  theme(panel.grid = element_blank()) +
  labs(x = NULL, y = NULL, fill = "# trips") +
  coord_fixed()
```

```{r}
stop_times <- read_csv("stop_times.txt", col_types= cols(arrival_time = col_character(), departure_time = col_character()))

stop_times <- stop_times %>% 
  left_join(trips) %>% 
  left_join(routes) %>% 
  select(route_id, route_short_name, trip_id, stop_id, service_id, arrival_time, departure_time, direction_id, shape_id, stop_sequence)

head(stop_times)

trips %>% 
  group_by(service_id) %>% 
  count(service_id) %>%
  arrange(desc(n))

stop_times <- stop_times %>% 
  filter(
    stop_sequence == 1 & 
      direction_id == 0 &
      service_id == trips$service_id)
 
head(stop_times)

stop_times <- stop_times %>% 
  mutate(
    arrival_time = ifelse(
      as.integer(substr(arrival_time, 1, 2)) < 24,
      as.integer(substr(arrival_time, 1, 2)),
      as.integer(substr(arrival_time, 1, 2)) - 24),
    departure_time = ifelse(
      as.integer(substr(departure_time, 1, 2)) < 24,
      as.integer(substr(departure_time, 1, 2)),
      as.integer(substr(departure_time, 1, 2)) -24)
    )
head(stop_times)

output_data <- stop_times %>% 
  group_by_at(vars(route_id, route_short_name, arrival_time)) %>% 
  count(arrival_time)
head(output_data)

output_data <- stop_times %>% 
  group_by_at(vars(route_id, route_short_name, arrival_time)) %>% 
  count(arrival_time) %>% 
  mutate(time_window = paste(arrival_time, '00', sep = ':')) %>% 
  select(route_id, route_short_name, arrival_time, time_window, n)
head(output_data)

output_data$time_window <- factor(output_data$time_window, levels = unique(output_data$time_window))
```


```{r}
g_line <- ggplot(data = output_data,
            aes(x = time_window, y = n, group = 1)) + 
  geom_line(color = 'steelblue') +
  geom_point(color = 'steelblue') +
  geom_text(aes(label = n), 
            vjust = -0.8,
            color = "black",
            size = 3) +
  scale_fill_brewer(palette="Dark2")+
  facet_wrap(~route_id)
  labs(title = paste('Trips by hour for route', output_data$route_short_name, sep = ' '),
        x = "Time window",
        y = '') +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.line.x = element_line(colour = "grey"),
        axis.line.y = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text.y = element_blank(),
        axis.ticks.x = element_line(colour = "grey"),
        axis.ticks.y = element_blank(),
        plot.title = element_text(hjust = 0.5)
        )
g_line
```

```{r}
install.packages("stplanr")
install.packages("r5r")
install.packages("geosphere")
install.packages("osrm")
library(stplanr)
library(geosphere)
library(osrm)
library(r5r)
library(rJava)

stop_ids <- gtfs$stops$stop_id
stop_pairs <- t(combn(stop_ids, 2))

stop_geom <- stops %>% select(stop_id, geometry)
stop_geom <- stop_geom %>%
    mutate(long = unlist(map(stop_geom$geometry,1)),
           lat = unlist(map(stop_geom$geometry,2)))
stop_geom <- as.data.frame(stop_geom)
stop_geom <- stop_geom %>%
  select(stop_id, long, lat)

colnames(stop_geom) <- c("V1", "O_Long", "O_Lat")

stop_geom_2 <- stop_geom
colnames(stop_geom_2) <- c("V2", "D_Long", "D_Lat")

stops2 <- stop_geom
colnames(stops2) <- c("stop_id", "stop_lon", "stop_lat")

stop_pairs <- subset(stop_pairs, stop_pairs[,1] != stop_pairs[,2])
stop_pairs <- as.data.frame(stop_pairs)

stop_pairs <- left_join(stop_pairs, stop_geom, by = "V1")
stop_pairs <- left_join(stop_pairs, stop_geom_2, by = "V2")

dist_mat <- apply(stop_pairs, 1, function(x) distm(stops2[stops2$stop_id == x[1], c("stop_lon", "stop_lat")], stops2[stops2$stop_id == x[2], c("stop_lon", "stop_lat")]))

options(java.parameters = "-Xmx2G")
path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path = path, verbose = FALSE)

ttm <- travel_time_matrix(
  r5r_core,
  origins = points,
  destinations = points,
  mode = "TRANSIT",
  max_trip_duration = 60
)
head(ttm)

```




#https://www.youtube.com/watch?v=xu1jpGKFSvY
#https://cran.r-project.org/web/packages/tidytransit/vignettes/servicepatterns.html